### ISSUE TITLE
ChildNodes showing wrong count

### ISSUE THREAD

**Issue by GayathriB1010** [anshooarora/extentreports-java#580] opened 2016-08-08 07:29 UTC
Hi,

I changed jar to extent reports 2.41.1, Still I am getting wrong count, when configuring as only child nodes.
![child tests issue](https://cloud.githubusercontent.com/assets/20083154/17472347/f003c1fc-5d67-11e6-8cb4-b6922a973b35.png)

**Comment by anshooarora** [comment] 2016-08-08 16:59
duplicate of #573.

As stated in #573, you need to insert this code in config.xml:

```
$('#childNodes').click();
$('#test-count-setting .modal-action').click();
```

and use `loadConfig` to load the file at runtime.

```
<?xml version="1.0" encoding="UTF-8"?>
<extentreports>
    <configuration>
        <!-- report theme -->
        <!-- standard, dark -->
        <theme>standard</theme>
    
        <!-- document encoding -->
        <!-- defaults to UTF-8 -->
        <encoding>UTF-8</encoding>
        
        <!-- protocol for script and stylesheets -->
        <!-- defaults to https -->
        <protocol>https</protocol>
        
        <!-- title of the document -->
        <documentTitle>ExtentReports 2.0</documentTitle>
        
        <!-- report name - displayed at top-nav -->
        <reportName>Automation Report</reportName>
        
        <!-- report headline - displayed at top-nav, after reportHeadline -->
        <reportHeadline></reportHeadline>
        
        <!-- global date format override -->
        <!-- defaults to yyyy-MM-dd -->
        <dateFormat>yyyy-MM-dd</dateFormat>
        
        <!-- global time format override -->
        <!-- defaults to HH:mm:ss -->
        <timeFormat>HH:mm:ss</timeFormat>
        
        <!-- custom javascript -->
        <scripts>
            <![CDATA[
                $(document).ready(function() {
                    $('#childNodes').click();
                    $('#test-count-setting .modal-action').click();
                });
            ]]>
        </scripts>
        
        <!-- custom styles -->
        <styles>
            <![CDATA[
                
            ]]>
        </styles>
    </configuration>
</extentreports>
```

**Closed by anshooarora** 2016-08-08 16:59 UTC
Labels: duplicate
