### ISSUE TITLE
Search Feature in report doesn't work intermittently

### ISSUE THREAD

**Issue by mayurgoenka** [anshooarora/extentreports-java#809] opened 2017-03-18 20:01 UTC
Search feature in Extent Reports stops working intermittently. I need to refresh the page for it to make it work. What's wrong?

**Comment by email2vimalraj** [comment] 2017-03-19 19:05
Attach your report for us to reproduce.

**Comment by anshooarora** [comment] 2017-03-20 15:20
Please share the steps to repro also.  Which view does it fail on?

**Comment by mayurgoenka** [comment] 2017-03-20 15:43
Check the category tab and try the search feature.

https://drive.google.com/file/d/0B2UToIzi4OOuM3d3cnRGVngxcFE/view?usp=sharing

**Comment by mayurgoenka** [comment] 2017-03-20 15:44
The search feature stops working in the main view as well sometimes but i don't have the steps to reproduce that issue.

**Comment by anshooarora** [comment] 2017-03-20 17:03
Thanks, I am able to repro.  Since you have opened #818,  I am closing this and marking #818 as a bug.

**Closed by anshooarora** 2017-03-20 17:03 UTC

**Comment by mayurgoenka** [comment] 2017-03-20 17:22
both are different issues:
one is about the search bar
other is about the category based filter in the main view

Just wanted to confirm if you understood the above. Thanks!
