### ISSUE TITLE
How can I edit the dash board of extent reports?

### ISSUE THREAD

**Issue by GayathriB1010** [anshooarora/extentreports-java#565] opened 2016-07-27 10:00 UTC
![extentreportdashboard](https://cloud.githubusercontent.com/assets/20083154/17171526/b7e2c762-540e-11e6-9d8f-a1166ea49edb.png)

In the attached dash board, I have 8 tests passed and 3 tests failed. I have 8 child nodes and 3 parent. I want to get the status of tests in child tests only. How can i edit it in the dashboard? I am using parent tests only to append child tests and not using for getting status

**Comment by anshooarora** [comment] 2016-07-28 15:06
Possible duplicate of #289.  

See [here](https://github.com/anshooarora/extentreports-java/issues/289#issuecomment-172894657) for the solution.

**Closed by anshooarora** 2016-07-28 15:06 UTC

**Comment by GayathriB1010** [comment] 2016-08-01 12:54
I added the code in extent-config.xml. The config option is getting selected, but save button is not clicked. 
Can I edit the script.js jar and add the code there?
