### ISSUE TITLE
Screenshots from previous execution are not displayed

### ISSUE THREAD

**Issue by Akhilesh-123** [anshooarora/extentreports-java#734] opened 2017-01-09 13:52 UTC
Screenshots of the previous run are not displayed. I am just seeing the Red cross mark.
![missing_screenshot](https://cloud.githubusercontent.com/assets/10736957/21768800/8ba416cc-d6a1-11e6-823b-6674c52633cd.jpg)

ExtentReports(String filePath, Boolean false)  -I am seeing the previous steps but the Screenshots are missing.

**Comment by savvyaxnjxn** [comment] 2017-01-09 14:51
Yes!  I believe this may be a duplicate of the issue I entered, #726 (v3.0.1 Extent Report - Screenshots only appear for the most recently executed test).  I *am* able to see my most recently executed test, but the remainder of the previous executions disappear.  My screenshot files are actually present, but they are no longer referenced in my extentReport.html.

**Comment by anshooarora** [comment] 2017-01-12 04:26
duplicate #726 

Also - a potential solution if you are using `setAppendExisting` is to attach screenshots to logs directly:

```
// adding screenshots to log
test.fail("details", MediaBuilder.createScreenCaptureFromPath("screenshot.png").build());

// or:
MediaModelProvider mediaModel = MediaBuilder.createScreenCaptureFromPath("screenshot.png").build();
test.fail("details", mediaModel);	
```

Source: http://extentreports.com/docs/versions/3/java/#insert-screenshots

**Closed by anshooarora** 2017-01-12 04:26 UTC
