### ISSUE TITLE
Need Example of BDD style using TestNG ,Cucumber and Extent report 3

### ISSUE THREAD

**Issue by perwez123** [anshooarora/extentreports-java#784] opened 2017-02-27 06:31 UTC
Hi Anshoo,

I checked the document in extent report website but could not find any example of BDD style implementation using cucumber and TestNG and extent report. It has only the API that needs to be used for example , GIVEN , when , then etc . 

Please provide the sample with implementation of Extent report using TestNG , Cucumber or update the same in the website .

It would be help for the people who is visiting the website for the first time or they don't how to integrate using cucumber.

I am just asking you to update the example in your website , not to help me personally. Once you have updated this, then I can get it from there.

Your help is appreciated

**Comment by anshooarora** [comment] 2017-02-28 19:13
I would suggest checking @email2vimalraj first to add support to CucumberExtentReporter for version 3+.

**Comment by perwez123** [comment] 2017-03-01 06:01
@email2vimalraj @anshooarora Thank you so much for your reply. I think it would much desirable to get support for Junit runner and TestNG as well to enjoy its features as soon as possible.

You must develop this keeping in mind that, User has the expectation to get support for the parallel test report using categorization.And update the same into your website.

Thank you so much again

**Comment by email2vimalraj** [comment] 2017-03-01 06:10
@perwez123: The problem is that Cucumber with TestNG, the testng listener
cannot intercept the cucumber features and scenarios. It can understand
only the testng classes and methods. So we'll have to merge the listeners
of both cucumber and testng to get an unified solution to your problem.
However this is the real use-case where lots of people use TestNG with
Cucumber, so it has to be worked upon.

I've already started investigating this feature and expecting to come up
with a new release on cucumber extent reporter during this weekend. Kindly
hold on still.

Thanks
Vimalraj

**Comment by perwez123** [comment] 2017-03-01 06:42
@email2vimalraj , I am happy to hear that you have started working on it to support TestNG.
One more thing is, I will be running the test in parallel and want single report for all.

Surely will wait until getting some workaround for this.Please let me know once it is done

Thanks
Perwez

**Comment by email2vimalraj** [comment] 2017-03-06 03:07
@perwez123 : A new release on the Cucumber Extent Report available now. Kindly give a try: https://github.com/email2vimalraj/CucumberExtentReporter

**Comment by perwezalamnewscorp** [comment] 2017-03-07 07:33
@email2vimalraj , Thank you so much for providing the support for BDD and extent report 3.

I tried your example and it worked fine. Now I have few question as when multiple test runner is ran, then will the one report will be generated for all runner. As I am seeing the report is flushed in After class it means after each test runner report will will be flushed .?

Another question , If I run in parallel mode using testNg , Will the single report will have all thread results ?

**Comment by email2vimalraj** [comment] 2017-03-07 08:11
> As I am seeing the report is flushed in After class it means after each test runner report will will be flushed .?

The report will not be flushed. You will see all the runner data in the report.

> Another question , If I run in parallel mode using testNg , Will the single report will have all thread results ?

I think so. It would be great if you can test and let me know.

**Comment by email2vimalraj** [comment] 2017-03-07 17:55
Let me take back my promises on the parallelism on TestNG. I see it is not happening. But running sequentially with multiple runners generates a single report with all feature information.

I'll dig deeper on the parallelism of cucumber, but I cannot assure anything, since cucumber itself natively not supporting parallelism yet.

**Comment by vvigneshbabu** [comment] 2017-03-20 13:48
Could you please provider the example for DOT Net BDD framework too

**Comment by email2vimalraj** [comment] 2017-03-20 15:40
@perwezalamnewscorp 

> Let me take back my promises on the parallelism on TestNG. I see it is not happening. But running sequentially with multiple runners generates a single report with all feature information.

I'll dig deeper on the parallelism of cucumber, but I cannot assure anything, since cucumber itself natively not supporting parallelism yet.

The issues were fixed in the latest version of Cucumber Extent Reporter. Kindly give a try and let me know.

**Comment by email2vimalraj** [comment] 2017-03-20 15:41
@vvigneshbabu : For .Net, kindly log it in: https://github.com/anshooarora/extentreports-csharp

**Comment by email2vimalraj** [comment] 2017-03-24 05:04
@perwez123 : Closing this issue. Kindly feel free to re-open in case you need any help.

If issue is related to Cucumber Extent Reporter, kindly report it in: https://github.com/email2vimalraj/CucumberExtentReporter

**Closed by email2vimalraj** 2017-03-24 05:04 UTC
