### ISSUE TITLE
Order of the reports attached to "attachReporter" method needs fix

### ISSUE THREAD

**Issue by srikanthvejendla** [anshooarora/extentreports-java#615] opened 2016-09-06 04:18 UTC
Order of the reports attached to "attachReporter" method needs fix

**Version:** extentReports[3.0.0-SNAPSHOT]

**Scenario #1:**

If extentHTMLReporter is the passed as the first param followed by extentXReporter, then extentx server is crashing(sails lift)

```
        ExtentXReporter extentXReporter  = new ExtentXReporter("127.0.0.1");
        extentXReporter.config().setProjectName(projectName);
        extentXReporter.config().setReportName(reportName);
        extentXReporter.config().setServerUrl("http://localhost:1337/");
        ExtentHtmlReporter extentHtmlReporter=new ExtentHtmlReporter("test-output/first.html");
        extentHtmlReporter.config().setTestViewChartLocation(ChartLocation.TOP);
        extentHtmlReporter.config().setChartVisibilityOnOpen(true);
        extentHtmlReporter.config().setTheme(Theme.STANDARD);
        extentHtmlReporter.config().setEncoding("utf-8");
        extentHtmlReporter.config().setReportName(reportName);
        extentHtmlReporter.config().setAutoCreateRelativePathMedia(true);
        extent = new ExtentReports();
        extent.attachReporter(extentHtmlReporter,extentXReporter);
```

Please refer the crash log at the bottom

**Scenario #2:** 

If extentXReporter is the passed as the first param followed by extentHtmlReporter, then screenshots are appearing fine in both reports(local/extentx)

```
        ExtentXReporter extentXReporter  = new ExtentXReporter("127.0.0.1");
        extentXReporter.config().setProjectName(projectName);
        extentXReporter.config().setReportName(reportName);
        extentXReporter.config().setServerUrl("http://localhost:1337/");
        ExtentHtmlReporter extentHtmlReporter=new ExtentHtmlReporter("test-output/first.html");
        extentHtmlReporter.config().setTestViewChartLocation(ChartLocation.TOP);
        extentHtmlReporter.config().setChartVisibilityOnOpen(true);
        extentHtmlReporter.config().setTheme(Theme.STANDARD);
        extentHtmlReporter.config().setEncoding("utf-8");
        extentHtmlReporter.config().setReportName(reportName);
        extentHtmlReporter.config().setAutoCreateRelativePathMedia(true);
        extent = new ExtentReports();
        extent.attachReporter(extentXReporter,extentHtmlReporter);
```

**Crash Log:**

```
error: Unable to parse HTTP body- error occurred :: 'Error: Request aborted\n    at IncomingMessage.onReqAborted (/Users/s0v0023/Documents/GitHub/extentx/node_modules/skipper/node_modules/multiparty/index.js:175:17)\n    at emitNone (events.js:86:13)\n    at IncomingMessage.emit (events.js:185:7)\n    at abortIncoming (_http_server.js:280:11)\n    at Socket.serverSocketCloseListener (_http_server.js:293:5)\n    at emitOne (events.js:101:20)\n    at Socket.emit (events.js:188:7)\n    at TCP._handle.close [as _onclose] (net.js:492:12)'
error: Sending 500 ("Server Error") response: 
 Error: Request aborted
    at IncomingMessage.onReqAborted (/Users/s0v0023/Documents/GitHub/extentx/node_modules/skipper/node_modules/multiparty/index.js:175:17)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at abortIncoming (_http_server.js:280:11)
    at Socket.serverSocketCloseListener (_http_server.js:293:5)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:492:12)
_http_outgoing.js:346
    throw new Error('Can\'t set headers after they are sent.');
    ^

Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:346:11)
    at ServerResponse.res.setHeader (/usr/local/lib/node_modules/sails/node_modules/express/node_modules/connect/lib/patch.js:134:22)
    at ServerResponse.res.set.res.header (/Users/s0v0023/Documents/GitHub/extentx/node_modules/express/lib/response.js:595:10)
    at ServerResponse.res.send (/Users/s0v0023/Documents/GitHub/extentx/node_modules/express/lib/response.js:151:12)
    at ServerResponse.res.json (/Users/s0v0023/Documents/GitHub/extentx/node_modules/express/lib/response.js:237:15)
    at ServerResponse.jsonx (/Users/s0v0023/Documents/GitHub/extentx/node_modules/sails/lib/hooks/responses/index.js:222:21)
    at Object.serverError (/Users/s0v0023/Documents/GitHub/extentx/api/responses/serverError.js:41:16)
    at ServerResponse.wrapper [as serverError] (/Users/s0v0023/Documents/GitHub/extentx/node_modules/sails/node_modules/lodash/index.js:3095:19)
    at Object.negotiate (/Users/s0v0023/Documents/GitHub/extentx/node_modules/sails/lib/hooks/responses/defaults/negotiate.js:41:14)
    at ServerResponse.wrapper [as negotiate] (/Users/s0v0023/Documents/GitHub/extentx/node_modules/sails/node_modules/lodash/index.js:3095:19)
    at whenDone (/Users/s0v0023/Documents/GitHub/extentx/api/controllers/FileController.js:21:28)
    at cb (/Users/s0v0023/Documents/GitHub/extentx/node_modules/skipper/standalone/Upstream/prototype.upload.js:82:14)
    at Upstream.<anonymous> (/Users/s0v0023/Documents/GitHub/extentx/node_modules/skipper/standalone/Upstream/prototype.upload.js:112:12)
    at Upstream.g (events.js:286:16)
    at emitOne (events.js:101:20)
    at Upstream.emit (events.js:188:7)
    at Upstream.fatalIncomingError (/Users/s0v0023/Documents/GitHub/extentx/node_modules/skipper/standalone/Upstream/prototype.fatalIncomingError.js:96:8)
    at /Users/s0v0023/Documents/GitHub/extentx/node_modules/skipper/lib/Parser/prototype.parseReq.js:51:10
    at Function.forEach (/Users/s0v0023/Documents/GitHub/extentx/node_modules/skipper/node_modules/lodash/dist/lodash.js:3298:15)
    at lodash.ctor.(anonymous function) [as each] (/Users/s0v0023/Documents/GitHub/extentx/node_modules/skipper/node_modules/lodash/dist/lodash.js:5925:31)
    at Form.<anonymous> (/Users/s0v0023/Documents/GitHub/extentx/node_modules/skipper/lib/Parser/prototype.parseReq.js:50:23)
    at emitOne (events.js:101:20)
```

**Comment by srikanthvejendla** [comment] 2016-09-06 04:19
@anshooarora Needs to fix "attachReporter" method params order

**Comment by anshooarora** [comment] 2016-09-07 21:50
I am unable to reproduce issues on both scenarios using the snapshot version on nexus.  What is your version of ExtentX?

**Comment by srikanthvejendla** [comment] 2016-09-07 21:53
extentx:0.2.1-alpha, 
extentreports: 3.0.0 Snapshot

**Comment by anshooarora** [comment] 2016-09-07 21:57
Os?

**Comment by anshooarora** [comment] 2016-09-07 21:58
Also, I believe the issue may be emmiting from this config of HTML-reporter:

```
setAutoCreateRelativePathMedia
```

Can you make it false or remove it and check again?

**Comment by srikanthvejendla** [comment] 2016-09-07 21:59
OS: Mac OS X 10.11.6

I will try and update the thread

**Comment by anshooarora** [comment] 2016-09-22 19:49
The latest commit of [extentx](https://github.com/anshooarora/extentx/commit/dab8697223c241d4fc3d0d7cdc6829da86d88acf) fixes issues with snapshots not showing up.  I would recommend removing this:

```
extentHtmlReporter.config().setChartVisibilityOnOpen(true);
```

It will not be available in the release version also, until all the issues are completely resolved.

**Comment by anshooarora** [comment] 2016-10-30 03:59
Issue has been fixed in version 3.

**Closed by anshooarora** 2016-10-30 03:59 UTC
Labels: bug
